<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\QNBFinansbank.CashManagement\QNBFinansbank.CashManagement.csproj" />
    <ProjectReference Include="..\QNBFinansbank.MoneyTransfer\QNBFinansbank.MoneyTransfer.csproj" />
    <ProjectReference Include="..\QNBFinansbank.VirtualPos\QNBFinansbank.VirtualPos.csproj" />
  </ItemGroup>

</Project>
